package loader

import (
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"testing"

	"golang.org/x/tools/go/ssa/ssautil"
)

// writeModule materializes files into a temp dir and returns its path.
func writeModule(t *testing.T, files map[string]string) string {
	t.Helper()
	dir := t.TempDir()
	for name, content := range files {
		path := filepath.Join(dir, name)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return dir
}

func TestLoadClassifiesFiles(t *testing.T) {
	dir := writeModule(t, map[string]string{
		"go.mod": "module example.com/tiny\n\ngo 1.22\n",
		"main.go": `package main

import "example.com/tiny/gen"

func main() { work(gen.Thing{}) }

func work(t gen.Thing) { helper() }

func helper() {}
`,
		"gen/thing.pb.go": `// Code generated by protoc-gen-go. DO NOT EDIT.
package gen

type Thing struct{ Name string }

func (t Thing) Reset() {}
`,
		"main_test.go": `package main

import "testing"

func TestNothing(t *testing.T) { onlyInTests() }

func onlyInTests() {}
`,
	})

	p, err := Load(dir)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	if p.Module != "example.com/tiny" {
		t.Errorf("Module = %q, want example.com/tiny", p.Module)
	}

	classes := map[string]FileClass{}
	for name, c := range p.fileClass {
		classes[filepath.Base(name)] = c
	}
	if classes["thing.pb.go"] != Generated {
		t.Errorf("thing.pb.go classified %v, want Generated", classes["thing.pb.go"])
	}
	if classes["main.go"] != Normal {
		t.Errorf("main.go classified %v, want Normal", classes["main.go"])
	}
	if _, ok := classes["main_test.go"]; ok {
		t.Error("main_test.go was loaded; Tests:false should exclude it")
	}

	gen, total := p.GeneratedStats()
	if gen != 1 {
		t.Errorf("GeneratedStats generated = %d, want 1 (Thing.Reset)", gen)
	}
	if total < 4 {
		t.Errorf("GeneratedStats total = %d, want >= 4", total)
	}

	for fn := range ssautil.AllFunctions(p.Prog) {
		switch fn.Name() {
		case "Reset":
			if p.FuncClass(fn) != Generated {
				t.Errorf("FuncClass(Reset) = %v, want Generated", p.FuncClass(fn))
			}
		case "work":
			if p.FuncClass(fn) != Normal {
				t.Errorf("FuncClass(work) = %v, want Normal", p.FuncClass(fn))
			}
			if !p.InModule(fn) {
				t.Error("InModule(work) = false, want true")
			}
		}
	}
}

func TestClassifyFileByName(t *testing.T) {
	tests := []struct {
		name    string
		content string
		want    FileClass
	}{
		{"api_gen.go", "package x\n", Generated},
		{"api.pb.go", "package x\n", Generated},
		{"api.go", "// Code generated by tool. DO NOT EDIT.\npackage x\n", Generated},
		{"api.go", "// Copyright notice.\npackage x\n", Normal},
		{"vendor/dep/api.go", "package x\n", Vendor},
	}
	for _, tt := range tests {
		f, err := parser.ParseFile(token.NewFileSet(), tt.name, tt.content, parser.ParseComments)
		if err != nil {
			t.Fatalf("parse %s: %v", tt.name, err)
		}
		if got := classifyFile("/mod/"+tt.name, f); got != tt.want {
			t.Errorf("classifyFile(%s) = %v, want %v", tt.name, got, tt.want)
		}
	}
}

func TestPositionRelative(t *testing.T) {
	dir := writeModule(t, map[string]string{
		"go.mod":       "module example.com/tiny\n\ngo 1.22\n",
		"sub/thing.go": "package sub\n\nfunc F() {}\n",
	})
	p, err := Load(dir)
	if err != nil {
		t.Fatalf("Load: %v", err)
	}
	for fn := range ssautil.AllFunctions(p.Prog) {
		if fn.Name() == "F" && p.InModule(fn) {
			if pos := p.Position(fn.Pos()); pos != "sub/thing.go:3" {
				t.Errorf("Position = %q, want sub/thing.go:3", pos)
			}
			return
		}
	}
	t.Fatal("function F not found")
}
