// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

// Package grpcapi simulates protoc-generated gRPC bindings: the server
// interface + Register function that entrypoint discovery keys on, and a
// client stub whose ClientConn.Invoke call must surface as a grpc effect.
package grpcapi

import (
	"context"

	grpc "google.golang.org/grpc"
)

type GetOrderReq struct{ Id string }
type GetOrderResp struct{ Item string }

type OrdersServer interface {
	GetOrder(ctx context.Context, req *GetOrderReq) (*GetOrderResp, error)
	mustEmbedUnimplementedOrdersServer()
}

type UnimplementedOrdersServer struct{}

func (UnimplementedOrdersServer) GetOrder(context.Context, *GetOrderReq) (*GetOrderResp, error) {
	return nil, nil
}
func (UnimplementedOrdersServer) mustEmbedUnimplementedOrdersServer() {}

func RegisterOrdersServer(s grpc.ServiceRegistrar, srv OrdersServer) {
	s.RegisterService(&ordersServiceDesc, srv)
}

var ordersServiceDesc = grpc.ServiceDesc{ServiceName: "toyshop.Orders"}

type OrdersClient struct{ cc *grpc.ClientConn }

func NewOrdersClient(cc *grpc.ClientConn) *OrdersClient { return &OrdersClient{cc: cc} }

func (c *OrdersClient) GetOrder(ctx context.Context, req *GetOrderReq, opts ...grpc.CallOption) (*GetOrderResp, error) {
	out := new(GetOrderResp)
	err := c.cc.Invoke(ctx, "/toyshop.Orders/GetOrder", req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}
